name: Arcade Compile

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v3

      - name: Make all
        run: make re

      - name: Make core
        run: make core

      - name: Make graphics
        run: make graphicals

      - name: Make Games
        run: make games
